In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%precision 3 
%matplotlib inline

In [8]:
df = pd.read_csv('ch4_scores400.csv')
scores = np.array(df['score'])
scores[:10]

array([76, 55, 80, 80, 74, 61, 81, 76, 23, 80])

In [13]:
np.random.choice([1,2,3], 3)

array([2, 2, 3])

In [22]:
np.random.choice([1,2,3], 3, replace=False)

array([1, 3, 2])

In [28]:
np.random.seed(0)
np.random.choice([1,2,3], 3)

array([1, 2, 1])

In [ ]:
np.random.seed